import React from 'react'

// Nextjs
import Head from 'next/head'

type LayoutProps = {
    children : any,
    title?: string
}

export default function Layout({children, title}: LayoutProps) {
    return (
        <div className=''>
            <Head>
                <title>{title || "Page title"}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='d-flex flex-column justify-content-between algin-items-center'>
                <main className='container-fluid min-vh-100 px-0 overflow-hidden'>
                    {children}
                </main>
            </div>
        </div>
    )
}
